server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:file:/database/ethanstore;MODE=PostgreSQL;DATABASE_TO_LOWER=true
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      poll-interval: 2s
